### ISSUE TITLE
Update to riot 2.4

### ISSUE THREAD

**Issue by brauliobo** [bjarosze/riot_js-rails#12]

**Comment by u007** [comment]
try my repo :)
https://github.com/u007/riot_js-rails

**Comment by brauliobo** [comment]
@bjarosze can you please add another maintainer to help with these updates? maybe @u007 or even me

**Comment by u007** [comment]
i created a pull request here
https://github.com/danbee/riot_js-rails/pull/1

**Comment by bjarosze** [comment]
For now I have no time to maintain this repo.

@brauliobo I've added you as collabolator.
@u007 You've created this pull request for another repo, so I can't merge it.

**Comment by u007** [comment]
sorry, here it is
https://github.com/bjarosze/riot_js-rails/pull/13

**Comment by brauliobo** [comment]
thanks @bjarosze, I'm reviewing #13. Please give access to brauliobo@gmail.com to push to rubygems

**Comment by bjarosze** [comment]
@brauliobo I've added you to rubygems.

**Comment by brauliobo** [comment]
released 0.4.1, can you please test @u007?
