### ISSUE TITLE
Cannot require `tag` files on application.js

### ISSUE THREAD

**Issue by guizero** [bjarosze/riot_js-rails#15]
Well, I have added the gem to the gemfile, runned bundle and added riot and riot_rails to the application.js (in my case, application.coffee).

Now I am struggling to add the tag I have just created to the application.coffee file. I've added it to the root of my `assets/javascripts` folder with the name `mytag.tag` and then required it like `#= mytag`, but that does not seem to work, event after adding the `js.tag` extension.

Any help?

**Comment by brauliobo** [comment]
try gem `riot_js-rails` instead
