### ISSUE TITLE
Include babel for ES6 support in Riot

### ISSUE THREAD

**Issue by brauliobo** [bjarosze/riot_js-rails#4]
If a `<script type="es6">` tag is used, Riot will need Babel to work.

**Comment by bjarosze** [comment]
I will check it today evening.

**Comment by bjarosze** [comment]
You can install babel via npm:
`npm install babel`

and next in bash:
`export NODE_PATH=/directory/to/your/node_modules`

**Comment by brauliobo** [comment]
@bjarosze execjs will use the system's node modules?

**Comment by bjarosze** [comment]
Execjs executes system command (node in this case), so I don't know reason why it shouldn't use system's modules (even if there is note in execjs FAQ that require is not available). I've tested it and looks it works.

**Comment by brauliobo** [comment]
ok, will try that soon, closing for now. thanks!

**Comment by brauliobo** [comment]
@bjarosze I have installed babel with `npm install -g babel` and `Error: Cannot find module 'babel'` is still returned. Should it be required on execjs?

**Comment by bjarosze** [comment]
I've pushed new version with option to set path to modules in `config/application.rb`:

```
config.riot.node_paths << '/path/to/your/node_modules'
```

If you do not provide this config, gem will use global modules.
