### ISSUE TITLE
Recommend therubyracer for better performance

### ISSUE THREAD

**Issue by brauliobo** [bjarosze/riot_js-rails#6]
Just as react-rails suggested, recommend therubyracer as it has a much better performance for executing javascript

**Comment by bjarosze** [comment]
Node is used only to compile assets. In production all assets will be precompiled, in development only assets that were changed are recompiled. Therefore changing JS engine will not improve performance too much.
Also Riot compiler use Node API and I'm not sure how to force Therubyracer to work with it. But you're welcome to create pull request that will allow to change JS engine.

**Comment by brauliobo** [comment]
@bjarosze This is not the case on server rendering.
I think therubyracer supports node API.

Anyway, will implement server rendering sooner or later..
