### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by brauliobo** [bjarosze/riot_js-rails#7]
The rubygem version is quite outdated (just saw it is still using class selector).

Please release and push a new version to rubygems.org.

I can do this if you need help.

**Comment by bjarosze** [comment]
I've just checked it and there is the newest version from 15 of September (https://rubygems.org/gems/riot_js-rails). 
Maybe you need `bundle update riot_js-rails`?

**Comment by brauliobo** [comment]
oops, missed that, sorry
