### ISSUE TITLE
node_runner is breaking assets compilation

### ISSUE THREAD

**Issue by justaskz** [bjarosze/riot_js-rails#9]
I get this error while trying to compile assets: `ExecJS::ProgramError: Unexpected character '#'`. 

After checking the source code, I found that in `node_runner` there is a strange line `#{source}`. Looks like Ruby interpolation. 

How should I fix this issue and start using riotjs?

```
(function(program, execJS) { execJS(program); })(function(module, exports, console) {
  #{source}
}, function(program) {
  var output, print = function(string) {
    process.stdout.write('' + string);
  };
  try {
    result = program();
    if (typeof result == 'undefined' && result !== null) {
      print('["ok"]');
    } else {
      try {
        print(JSON.stringify(['ok', result]));
      } catch (err) {
        print('["err"]');
      }
    }
  } catch (err) {
    print(JSON.stringify(['err', '' + err]));
  }
});
```

My Rails app environment settings:

```
Rails.application.configure do
  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local = false
  config.action_controller.perform_caching = true
  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.js_compressor = :uglifier
  config.assets.compile = false
  config.assets.digest = true
  config.log_level = :warn
  config.assets.precompile << %r{(^[^_\/]|\/[^_])[^\/]*$}
  config.i18n.fallbacks = true
  config.active_support.deprecation = :notify
  config.log_formatter = ::Logger::Formatter.new
  config.active_record.dump_schema_after_migration = false
  config.active_job.queue_adapter = :sidekiq
end
```

**Comment by bjarosze** [comment]
I cannot reproduce it. Can you post your Gemfile.lock and your tag code that fails to compile?

**Comment by justaskz** [comment]
Gemfile.lock https://gist.github.com/justaskz/e727b18b6e60bf1f7469

I get this error by just adding a gem to Gemfile. Thats the only change.

**Comment by bjarosze** [comment]
It shouldn't be a problem of `node_runner` and `#{source}`. This is how execjs runners look like and this one is almost the same as the one provided by execjs gem. 

Can you create simple example project with this error?

**Comment by justaskz** [comment]
Ok, we can close the issue, it was this line:

`config.assets.precompile << %r{(^[^_\/]|\/[^_])[^\/]*$}`

Thank you for help!
